### ISSUE TITLE
Use urldecode instead of rawurldecode for query parameters

### ISSUE THREAD

**Issue by kelunik** [amphp/uri#12]
See https://github.com/amphp/aerys/pull/193.

**Comment by rajuvishwas** [comment]
@kelunik, can you assign to me

**Comment by rajuvishwas** [comment]
PR - https://github.com/amphp/uri/pull/13

We could also use [parse_str](http://php.net/manual/en/function.parse-str.php) which automatically urldecode the key & value.

**Comment by kelunik** [comment]
@rajuvishwas `parse_str` has a different behavior regarding arrays, e.g. `foo[bar]=82`.
